CREATE DATABASE POOJADB;
SHOW DATABASES;
SELECT DATABASE();
USE POOJADB;

SELECT * FROM workertable;
SELECT * FROM TITLETABLE;
SELECT * FROM BONUSTABLE;

#1
SELECT FIRST_NAME AS WORKER_NAME
FROM WORKERTABLE;

#2
SELECT UCASE(FIRST_NAME)
FROM WORKERTABLE;

#3
SELECT DISTINCT(DEPARTMENT)
FROM WORKERTABLE;

#4
SELECT LEFT(FIRST_NAME,3)
FROM WORKERTABLE;

#5
SELECT POSITION("A"IN"AMITABH")
FROM WORKERTABLE;

#6
SELECT RTRIM(FIRST_NAME)
FROM WORKERTABLE;

#7
SELECT LTRIM(DEPARTMENT)
FROM WORKERTABLE;

#8
SELECT distinct(LENGTH(DEPARTMENT))
FROM WORKERTABLE;

#9
SELECT REPLACE(FIRST_NAME,"a","A")
FROM WORKERTABLE;

#10
SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS COMPLETE_NAME
FROM WORKERTABLE;

#11
SELECT * 
FROM WORKERTABLE
ORDER BY FIRST_NAME ASC;

#12
SELECT * 
FROM WORKERTABLE
ORDER BY FIRST_NAME ASC,DEPARTMENT DESC;

#13
SELECT * 
FROM WORKERTABLE
WHERE FIRST_NAME IN ("VIPUL","SATISH");

#14
SELECT * 
FROM WORKERTABLE
WHERE FIRST_NAME<>"VIPUL"OR"SATISH";

#15
SELECT * 
FROM WORKERTABLE
WHERE DEPARTMENT="ADMIN";

#16
SELECT *
FROM WORKERTABLE
WHERE FIRST_NAME LIKE "%A%";

#17
SELECT *
 FROM WORKERTABLE
 WHERE FIRST_NAME LIKE "%A";
 
#18
SELECT * 
FROM WORKERTABLE
WHERE FIRST_NAME LIKE "%H" AND LENGTH(FIRST_NAME)=6;

#19
SELECT *
FROM WORKERTABLE
WHERE SALARY BETWEEN 100000 AND 500000;

#20
SELECT * 
FROM WORKERTABLE
WHERE JOINING_DATE BETWEEN "2021-02-01" AND "2021-02-28";

#21
SELECT COUNT(*) 
FROM WORKERTABLE
WHERE DEPARTMENT="ADMIN";

#22
SELECT *
FROM WORKERTABLE
WHERE SALARY>=500000 AND SALARY<=100000;

#23
SELECT COUNT(*),DEPARTMENT
 FROM WORKERTABLE
 GROUP BY DEPARTMENT
 ORDER BY DEPARTMENT DESC;
 
#24
SELECT WT.FIRST_NAME,TT.WORKER_TITLE
FROM WORKERTABLE WT LEFT JOIN TITLETABLE TT 
ON WT.WORKER_ID=TT.WORKER_REF_ID
WHERE WORKER_TITLE="MANAGER";

#25
SELECT WORKER_ID,COUNT(*)
FROM WORKERTABLE
GROUP BY WORKER_ID
HAVING COUNT(*)>1;

#26
SELECT *
FROM WORKERTABLE
WHERE MOD(WORKER_ID,2)<>0;

#27
SELECT *
FROM WORKERTABLE
WHERE MOD(WORKER_ID,2)=0;

#28
SELECT *
FROM WORKERTABLE
ORDER BY SALARY
LIMIT 3;

#29
SELECT * FROM
(SELECT *,DENSE_RANK() 
OVER(ORDER BY SALARY DESC)
AS OS_SALARY 
FROM WORKERTABLE)
AS DS WHERE OS_SALARY=5;

#30
SELECT WT1.*
FROM WORKERTABLE WT1,WORKERTABLE WT2
WHERE WT1.SALARY=WT2.SALARY AND WT1.WORKER_ID<>WT2.WORKER_ID
ORDER BY WT1.SALARY;

#31
SELECT COUNT(WORKER_ID)
FROM WORKERTABLE
GROUP BY DEPARTMENT
HAVING COUNT(WORKER_ID)<5;

#32
SELECT DEPARTMENT,COUNT(WORKER_ID) AS NOP
FROM WORKERTABLE 
GROUP BY DEPARTMENT;

#33
SELECT *,RANK() OVER (ORDER BY SALARY DESC)
FROM WORKERTABLE
WHERE SALARY 
LIMIT 3;

#34
SELECT WT.FIRST_NAME,BT.BONUS_AMOUNT
FROM WORKERTABLE WT LEFT JOIN BONUSTABLE BT
ON WT.WORKER_ID=BT.WORKER_REF_ID;

#35
SELECT WT.DEPARTMENT,SUM(BT.BONUS_AMOUNT)
FROM WORKERTABLE WT LEFT JOIN BONUSTABLE BT
ON WT.WORKER_ID=BT.WORKER_REF_ID
GROUP BY WT.DEPARTMENT;

#36
SELECT WT.FIRST_NAME,TT.WORKER_TITLE
FROM WORKERTABLE WT LEFT JOIN TITLETABLE TT
ON WT.WORKER_ID=TT.WORKER_REF_ID;














 
